"""trade confirmations

Revision ID: 0011_trade_confirmations
Revises: 0010_user_skills

与 0010_user_skills 在两条分支上同时从 0009 长出，合并 main 时改接到它后面、改号 0011，
避免 alembic 出现两个 head（init_db 的 upgrade head 会直接报错）。
Create Date: 2026-09-14 22:49:46.552196
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0011_trade_confirmations'
down_revision: str | None = '0010_user_skills'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_confirmations',
    sa.Column('confirmation_id', sa.String(length=32), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('confirmation_id')
    )
    with op.batch_alter_table('trade_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_confirmations_operation_id'), ['operation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_trade_confirmations_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_confirmations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_confirmations_user_id'))
        batch_op.drop_index(batch_op.f('ix_trade_confirmations_thread_id'))
        batch_op.drop_index(batch_op.f('ix_trade_confirmations_operation_id'))

    op.drop_table('trade_confirmations')
    # ### end Alembic commands ###
