"""messages 加 images 列（user 轮的参考图文件名）

Revision ID: 54353b7b7e5a
Revises: 0004_usage_ledger
Create Date: 2026-07-14 17:35:50.777299
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005_message_images'
down_revision: str | None = '0004_usage_ledger'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
