"""memory tables: preferences / history_records / favorites

把用户级持久数据（长期偏好、行为历史、收藏）从 JSON 文件 / Redis 搬进关系库。

三张表的 user_id 都**不加外键**（与 threads 相反）：鉴权关闭时用户是不在 users 表里的 demo 身份，
外键会让每次写偏好直接炸。这三类数据的强度要求也本就低于账户——「偏好丢一条无所谓，账号丢一条
是事故」。只建 index 保查询。

Revision ID: 0002_memory
Revises: 0001_accounts
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_memory"
down_revision: str | None = "0001_accounts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorites",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("item_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("price_usd", sa.Float(), nullable=True),
        sa.Column("landed_usd", sa.Float(), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_fav_user_item"),
    )
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_favorites_user_id"), ["user_id"], unique=False)

    op.create_table(
        "history_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("source_session", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_records_user_id"), ["user_id"], unique=False)

    op.create_table(
        "preferences",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("polarity", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("domain", sa.String(length=32), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("content", sa.String(length=500), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("source_session", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedup_key", name="uq_pref_user_key"),
    )
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_preferences_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preferences", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_preferences_user_id"))

    op.drop_table("preferences")
    with op.batch_alter_table("history_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_history_records_user_id"))

    op.drop_table("history_records")
    with op.batch_alter_table("favorites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_favorites_user_id"))

    op.drop_table("favorites")
    # ### end Alembic commands ###
