"""memory_facts

长期记忆换模型：``preferences``（polarity/domain/slug 拼 dedup_key）→ ``memory_facts``
（user_id + fact_key 唯一，同 key 覆盖）。**不 drop 旧 preferences 表**：留一版作回滚依据，
数据由 ``scripts/migrate_preferences_to_facts.py`` 单独搬（计划 §4.1 C4）。

Revision ID: 0012_memory_facts
Revises: 0011_trade_confirmations
Create Date: 2026-09-19 16:06:22.155136
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0012_memory_facts'
down_revision: str | None = '0011_trade_confirmations'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.Column('fact_value', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('source_session', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'fact_key', name='uq_fact_user_key')
    )
    with op.batch_alter_table('memory_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_facts_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default 是 autogenerate 漏掉的、线上必炸的一项：给一张已有行的表加 NOT NULL 列，
        # 没有默认值时老行填不出值（SQLite batch 重建表、MySQL 直接 ADD COLUMN 都一样）。
        # 本地测试库每次重建所以照样绿，gcjp 那份老库才会现形。
        batch_op.add_column(
            sa.Column('memory_purge_gen', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('memory_purge_gen')

    with op.batch_alter_table('memory_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_facts_user_id'))

    op.drop_table('memory_facts')
    # ### end Alembic commands ###
